services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports: 
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: "no"
    # depends_on:
    #   mongodb:
    #     condition: service_healthy
    networks:
      - app-network
    command: python -m assistant.main

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password
    restart: always
    networks:
      - app-network


  langfuse-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=langfuse
      - POSTGRES_PASSWORD=langfuse_password
      - POSTGRES_DB=langfuse
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langfuse"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - langfuse_db_data:/data/langfuse_db_data
    networks:
      - app-network


  langfuse:
    image: langfuse/langfuse:2
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://langfuse:langfuse_password@langfuse-db:5432/langfuse
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=Nyz3HXp6NX6BAOiXOkXtpKdwVnXTvj_aqEK5pl-S2_4
      - SALT=SsKOz8LuDkL5gElDC1KGgNcBBpelmEJskEIvLAV5iC8
      - TELEMETRY_ENABLED=true
      - LANGFUSE_PUBLIC_KEY=pk-lf-2e3d79f8-c97e-43c5-ae63-0ba7c397fa9c
      - LANGFUSE_SECRET_KEY=sk-lf-b58b6b31-0aa6-4cad-a00c-9720d0c078ff
    depends_on:
      langfuse-db:
        condition: service_healthy
    restart: always
    networks:
      - app-network


  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: always
    networks:
      - app-network


volumes:
  mongodb_data:
  langfuse_db_data:

networks:
  app-network:
    driver: bridge
